=== DACUS1995/StructuredInformation-Course-Project/assets/xml/store.dtd
<!DOCTYPE brands
[
<!ELEMENT brands (brand)*>
<!ELEMENT brand (brand_name,worth,origin_country,number_of_employees,owner, image_logo,car_models)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT worth (#PCDATA)>
<!ELEMENT origin_country (#PCDATA)>
<!ELEMENT number_of_employees (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT image_logo (#PCDATA)>
<!ELEMENT car_models (model)*>
<!ELEMENT model (name,type,width,length,max_speed,number_of_doors,image)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ATTLIST width unit CDATA "meters">
<!ELEMENT length (#PCDATA)>
<!ATTLIST length unit CDATA "meters">
<!ELEMENT max_speed (#PCDATA)>
<!ELEMENT number_of_doors (#PCDATA)>
<!ELEMENT image (#PCDATA)>
]>

=== DACUS1995/StructuredInformation-Course-Project/assets/xml/store.xml
<?xml version="1.0" encoding = "UTF-8" standalone = "no" ?>
<!DOCTYPE brands SYSTEM "store.dtd">
<brands>
    <brand>
        <brand_name>Mercedes</brand_name>
        <worth>1</worth>
        <origin_country>Germany</origin_country>
        <number_of_employees>2000</number_of_employees>
        <owner>Name</owner>
        <image_logo>./assets/images/Mercedes/logo.jpg</image_logo>
        <car_models>
            <model>
                <name>A-Class</name>
                <type>Hatchback</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/Mercedes/car-a.jpg</image>
            </model>
            <model>
                <name>A-Class</name>
                <type>Hatchback</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/Mercedes/car-a.jpg</image>
            </model>
            <model>
                <name>A-Class</name>
                <type>Hatchback</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/Mercedes/car-a.jpg</image>
            </model>
            <model>
                <name>A-Class</name>
                <type>Hatchback</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/Mercedes/car-a.jpg</image>
            </model>
        </car_models>
    </brand>
    <brand>
        <brand_name>BMW</brand_name>
        <worth>2</worth>
        <origin_country>Germany</origin_country>
        <number_of_employees>2001</number_of_employees>
        <owner>Name2</owner>
        <image_logo>./assets/images/BMW/logo.jpg</image_logo>        
        <car_models>
            <model>
                <name>M5</name>
                <type>sedan</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/BMW/car-m5.jpg</image>
            </model>
            <model>
                <name>M3</name>
                <type>sedan</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/BMW/car-m5.jpg</image>
            </model>
            <model>
                <name>M4</name>
                <type>sedan</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/BMW/car-m5.jpg</image>
            </model>
            <model>
                <name>M3</name>
                <type>sedan</type>
                <width unit="meters">1.992</width>
                <length unit="meters">4.419</length>
                <max_speed>260</max_speed>
                <number_of_doors>4</number_of_doors>
                <image>./assets/images/BMW/car-m5.jpg</image>
            </model>
        </car_models>
    </brand>
</brands>
